
//LISTAR:
GET http://localhost:8080/api/productos/listar HTTP/1.1
Content-Type: application/json
    //Listar todos los productos.
###

GET http://localhost:8080/api/productos/listar/2 HTTP/1.1
Content-Type: application/json
    //Listar un producto en especial (modificar idParam)
###

//AGREGAR PRODUCTOS:
POST http://localhost:8080/api/productos/agregar HTTP/1.1
Content-Type: application/json
    //Añadir un producto a la 'base de datos'.

    {
        "name":"Cactus",
        "description":"Descripcion de cactus",
        "image":"https://firebasestorage.googleapis.com/v0/b/deco-etcetera.appspot.com/o/cuadro2.jpg?alt=media&token=05211aa9-1d31-461e-9755-3984def842a9",
        "price":250,
        "stock":30
    }
###

PUT http://localhost:8080/api/productos/actualizar/1 HTTP/1.1
Content-Type: application/json
    //Modificar producto (Cambiar valor en alguno de los campos debajo, y seleccionar producto en idParam)
{
        "name":"Cambio de nombre",
        "description":"Descripcion de cactus",
        "image":"https://firebasestorage.googleapis.com/v0/b/deco-etcetera.appspot.com/o/cuadro2.jpg?alt=media&token=05211aa9-1d31-461e-9755-3984def842a9",
        "price":250,
        "stock":30
    }
###

DELETE http://localhost:8080/api/productos/eliminar/14 HTTP/1.1
Content-Type: application/json
    //Eliminar producto (Modificar idParam en ruta)

###